language: ruby
rvm:
  - 2.3.0
  - 2.2.3
  - 2.1.0
  - 2.0.0
  - ruby-head
  - rbx
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/968de5e2c7eb03759e38
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: never     # options: [always|never|change] default: always
